name: artbeat_admin
description: "ARTbeat administrator module"
publish_to: "none"
version: 0.0.2
homepage: https://github.com/kristybock/artbeat

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter
  artbeat_core:
    path: ../artbeat_core
  artbeat_events:
    path: ../artbeat_events
  artbeat_ads:
    path: ../artbeat_ads
  artbeat_capture:
    path: ../artbeat_capture
  artbeat_artwork:
    path: ../artbeat_artwork
  artbeat_community:
    path: ../artbeat_community
  artbeat_art_walk:
    path: ../artbeat_art_walk
  artbeat_messaging:
    path: ../artbeat_messaging
  google_fonts: ^7.1.0
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  firebase_storage: ^13.0.6
  firebase_remote_config: ^6.1.1
  firebase_app_check: ^0.4.1+4
  cloud_functions: ^6.0.0
  provider: ^6.1.1
  flutter_secure_storage: ^9.0.0
  jwt_decoder: ^2.0.1
  uuid: ^4.2.1
  image_picker: ^1.1.2
  http: ^1.2.1
  logging: ^1.2.0
  intl: ^0.20.2
  path_provider: ^2.1.5
  share_plus: ^11.0.0
  url_launcher: ^6.3.1
  easy_localization: ^3.0.7

flutter:
  uses-material-design: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
