name: artbeat
description: "Local ARTbeat - A modular Flutter application for artists, galleries, and art lovers."
publish_to: "none"

version: 2.5.1+95

environment:
  sdk: ">=3.10.7 <4.0.0"
  flutter: ">=3.38.7"

dependencies:
  artbeat_admin:
    path: packages/artbeat_admin
  artbeat_ads:
    path: packages/artbeat_ads
  artbeat_art_walk:
    path: packages/artbeat_art_walk
  artbeat_artist:
    path: packages/artbeat_artist
  artbeat_artwork:
    path: packages/artbeat_artwork
  artbeat_auth:
    path: packages/artbeat_auth
  artbeat_capture:
    path: packages/artbeat_capture
  artbeat_community:
    path: packages/artbeat_community
  artbeat_core:
    path: packages/artbeat_core
  artbeat_events:
    path: packages/artbeat_events
  artbeat_messaging:
    path: packages/artbeat_messaging
  artbeat_profile:
    path: packages/artbeat_profile
  artbeat_settings:
    path: packages/artbeat_settings
  artbeat_sponsorships:
    path: packages/artbeat_sponsorships
  audioplayers: ^6.0.0
  cached_network_image: ^3.4.1
  camera: ^0.11.1
  cloud_firestore: ^6.1.2
  crypto: ^3.0.3
  cupertino_icons: ^1.0.8
  device_info_plus: ^12.3.0
  easy_localization: ^3.0.7
  file_picker: ^10.3.8
  firebase_analytics: ^12.1.1
  firebase_app_check: ^0.4.1+4
  firebase_auth: ^6.1.4
  firebase_core: ^4.4.0
  firebase_data_connect: ^0.2.2+2
  firebase_messaging: ^16.1.1
  firebase_storage: ^13.0.6
  flag: ^7.0.2
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  flutter_dotenv: ^6.0.0
  flutter_image_compress: ^2.3.0
  flutter_local_notifications: ^19.5.0
  flutter_markdown_plus: ^1.0.5
  flutter_sound: ^9.2.13
  flutter_svg: ^2.1.0
  geocoding: ^4.0.0
  geolocator: ^14.0.1
  google_fonts: ^7.1.0
  google_maps_flutter: ^2.5.3
  google_sign_in: ^7.2.0
  http: ^1.4.0
  image_cropper: ^11.0.0
  image_editor_plus: ^1.0.4
  image_picker: ^1.0.0
  in_app_purchase: ^3.2.3
  in_app_purchase_android: ^0.4.0+6
  in_app_purchase_storekit: ^0.4.6
  intl: ^0.20.2
  local_auth: ^3.0.0
  logging: ^1.2.0
  package_info_plus: ^9.0.0
  path_provider: ^2.1.5
  pedometer: ^4.0.2
  permission_handler: ^12.0.1
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  sign_in_with_apple: ^7.0.1
  video_player: ^2.8.2

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/translations/
    - assets/default_artwork.png
    - assets/default_profile.png
    - assets/event_placeholder.png
    - assets/event_placeholder.svg
    - assets/logo.png
    - assets/triangle.png
    - assets/images/subtle_pattern.png
    - assets/artist_onboarding_hero.png

  # Fonts
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
    - family: Limelight
      fonts:
        - asset: assets/fonts/Limelight/Limelight-Regular.ttf

dev_dependencies:
  build_runner: ^2.10.5
  build_test: ^3.5.5
  fake_cloud_firestore: ^4.0.0
  firebase_auth_mocks: ^0.15.1
  firebase_auth_platform_interface: any
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.4.4

dependency_overrides:
  archive: ^4.0.0
  screenshot: ^3.0.0
