name: artbeat_community
description: Social and community features for ARTbeat app
version: 0.0.2
publish_to: "none"

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter
  artbeat_core:
    path: ../artbeat_core
  artbeat_ads:
    path: ../artbeat_ads
  artbeat_art_walk:
    path: ../artbeat_art_walk
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  image_picker: ^1.0.7
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  timeago: ^3.6.0
  intl: ^0.20.2
  provider: ^6.1.1
  artbeat_artist:
    path: ../artbeat_artist
  artbeat_artwork:
    path: ../artbeat_artwork
  artbeat_events:
    path: ../artbeat_events
  artbeat_messaging:
    path: ../artbeat_messaging
  share_plus: ^11.0.0
  google_maps_flutter: ^2.5.3
  flutter_svg: ^2.0.10+1
  profanity_filter: ^2.0.0
  url_launcher: ^6.2.5
  flutter_stripe: ^12.1.0
  uuid: ^4.2.1
  geolocator: ^14.0.1
  http: ^1.2.0
  xml: ^6.5.0
  path_provider: ^2.1.5
  flutter_image_compress: ^2.3.0
  video_player: ^2.8.2
  audioplayers: ^6.0.0
  image_editor_plus: ^1.0.4
  file_picker: ^8.0.0+1
  easy_localization: ^3.0.7

flutter:
  uses-material-design: true
  assets:
    - assets/default_artwork.png
    - assets/default_profile.png
    - assets/images/communityicons/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.9
  cloud_firestore_platform_interface: any
