name: artbeat_sponsorships
description: Local ARTbeat sponsorships, promotions, and business advertising
publish_to: "none"

version: 0.1.0

environment:
  sdk: "^3.8.0"
  flutter: ">=3.35.0"

dependencies:
  artbeat_auth:
    path: ../artbeat_auth
  artbeat_core:
    path: ../artbeat_core
  cloud_firestore: ^6.1.2
  firebase_auth: ^6.1.4
  flutter:
    sdk: flutter
  geolocator: ^14.0.1
  google_maps_flutter: any
  intl: ^0.20.2
  provider: ^6.1.5
dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
