name: artbeat_art_walk
description: Art Walk features for ARTbeat app
version: 0.0.2
publish_to: "none"

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter
  artbeat_core:
    path: ../artbeat_core
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  google_maps_flutter: ^2.5.3
  provider: ^6.1.1
  crypto: ^3.0.3
  google_fonts: ^6.2.1
  google_maps_flutter_android: ^2.6.2
  google_maps_flutter_platform_interface: ^2.4.3
  geolocator: ^14.0.1
  geocoding: ^4.0.0
  share_plus: ^11.0.0
  image_picker: ^1.0.7
  logger: ^2.0.2
  shared_preferences: ^2.2.2
  http: ^1.2.0
  timeago: ^3.6.0
  device_info_plus: ^11.5.0
  image_cropper: ^9.1.0
  equatable: ^2.0.5
  intl: ^0.20.2
  confetti: ^0.8.0
  lottie: ^3.3.2
  flutter_tts: ^4.2.0
  cached_network_image: ^3.3.1
  geoflutterfire_plus: ^0.0.3
  pedometer: ^4.0.2
  logging: ^1.2.0
  easy_localization: ^3.0.7

  artbeat_capture:
    path: ../artbeat_capture
  artbeat_ads:
    path: ../artbeat_ads
  artbeat_settings:
    path: ../artbeat_settings
  artbeat_community:
    path: ../artbeat_community

flutter:
  uses-material-design: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.10
  cloud_firestore_platform_interface: any
  firebase_core_platform_interface: ^6.0.0
